### ISSUE TITLE
tables must be added before @relationship directives

### ISSUE THREAD

**Issue by jacobhausler** [charlieschwabacher/gestalt#10]
'gestalt migrate' must be run with a relationship-less schema to creates before you can add @relationship directives because the query is built in the order that the schema is written, and tables must be created before you can add indexes onto them.

Proposal: strip fields with @relationship out of the schema before generating the table-building query, then ALTER the tables to add relationships with a second query (or add it on the end of the first query).

**Comment by charlieschwabacher** [comment]
Yes! noticed you had that in the readme in your repo and was wondering why - it's because when it generates migrations, it adds the tables in the order they are defined in `schema.graphql`, so it's possible that the `REFERENCES` constraints on foreign keys to refer to tables that haven't yet been created.  I think your suggestion is the right approach.

Thanks for catching all of these!

**Comment by charlieschwabacher** [comment]
Just published 0.0.17 - the generated migrations now add foreign key constraints after all tables have been created
