### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by BjornMelgaard** [charlieschwabacher/gestalt#25]
What about it?)

**Comment by charlieschwabacher** [comment]
Hey Bjorn - gestalt is using flow internally, but its types are pretty heavily dependent on flow types exported by graphql-js.  Because graphql-js doesn't support typescript directly, I'm not likely to add them to the existing packages.

I'm not deeply familiar w/ typescript, but maybe the best way to achieve this would be a separate package similar to https://github.com/nitintutlani/typed-graphql ?
